# YetiHome config file.
#
# settings:
# messages: Plugin messages are stored here. Customize messages using these entries. Missing entries will not be sent.
# tooManyParameters: Message for when user specifies too many parameters. Variables: none
# defaultHomeSetMessage: Message for when default home is set. Variables: none
# cannotDeleteDefaultHomeMessage: Message for when player tries to delete deafult home. Variables: none
# homeSetMessage: Message for when home is set. Variables: {HOME}
# homeDeletedMessage: Message for when home deleted. Variables: {HOME}
# noHomeMessage: Message for when home not found. Variables: {HOME}
# noDefaultHomeMessage: Message for when default home not found.
# noPlayerMessage: Message for when target player not found. Variables: {PLAYER}'
# cooldownMessage: Message for when cooldown hasn't expired yet. Variables: {SECONDS}
# tooManyHomesMessage: Message for when user tries to set too many homes. Variables: {CURRENT}, {MAX}
# homeListMessage: Message for when home locations listed. Variables: {LIST}
# homeListOthersMessage: Message for when home locations for another player are listed. Variables: {PLAYER}, {LIST}
# econNotEnoughFunds: Message to use when a player does not have enough money for a command. Variables {AMOUNT}
# econDeductedForHome: Message to use when a player is charged for teleporting. Variables: {AMOUNT}
# econDeductForSet: Message to use when a player is charged for setting a home. Variables: {AMOUNT}
# deafult: Default settings for all users are stored here.
# cooldown: Amount of time to wait before /home can be used again.
# maxhomes: Maximum number of homes this group may have. Use -1 to signify no limit.
# setHomeCost: Amount to charge a player when setting their default home
#
# When editing this file for the first time, please duplicate the groups.default section
# for each of your defined Permissions groups.

YetiHome:
    enableHomeOnDeath: false
    permissiveGroupHandling: true
    enableEconomy: false
    loadChunks: false
    messages:
        tooManyParameters: 'Too many parameters.'
        defaultHomeSetMessage: 'You marked this area with your scent.'
        cannotDeleteDefaultHomeMessage: 'A yeti always needs a home.'
        homeSetMessage: 'Now the {HOME} smells like your land as well'
        homeDeletedMessage: 'The {HOME} no longer seems inviting.'
        noHomeMessage: '{HOME}? You know of no such place.'
        noDefaultHomeMessage: 'ForeverAlone without a home.'
        noPlayerMessage: 'Player {PLAYER} not found.'
        cooldownMessage: 'Your yeti powers have not recovered yet. Please wait another {MINUTES}m {SECONDS}s.'
        tooManyHomesMessage: 'You try to mark the area,but you have already marked {CURRENT} out of {MAX} areas.'
        homeListMessage: 'Home locations: {LIST}'
        homeListOthersMessage: 'Home locations for {PLAYER}: {LIST}'
        econNotEnoughFunds: 'You should possibly sell some fur. You lack {AMOUNT}TPs to do that.'
        econDeductedForHome: '{AMOUNT} was removed from your account for going home.'
        econDeductForSet: '{AMOUNT}TPs were paid to ensure your scent remains strong here'
    default:
        cooldown: 0
        maxhomes: -1
        setHomeCost: 0
        setNamedHomeCost: 0
        homeCost: 0
        namedHomeCost: 0
    groups:
        default:
            cooldown: 0
            maxhomes: -1
            setHomeCost: 0
            setNamedHomeCost: 0
            homeCost: 0
            namedHomeCost: 0