# YetiHome config file.
#
# settings:
# messages: Plugin messages are stored here. Customize messages using these entries. Missing entries will not be sent.
# tooManyParameters: Message for when user specifies too many parameters. Variables: none
# defaultHomeSetMessage: Message for when default home is set. Variables: none
# cannotDeleteDefaultHomeMessage: Message for when player tries to delete deafult home. Variables: none
# homeSetMessage: Message for when home is set. Variables: {HOME}
# homeDeletedMessage: Message for when home deleted. Variables: {HOME}
# noHomeMessage: Message for when home not found. Variables: {HOME}
# noDefaultHomeMessage: Message for when default home not found.
# noPlayerMessage: Message for when target player not found. Variables: {PLAYER}'
# warmupMessage: Message for when home warmup initiated. Variables: {SECONDS}
# warmupCompleteMessage: Message for when home warmup completes. Variables: none
# warmupDisruptMessage: Message for when home warmup is disrupted. Variables: none
# cooldownMessage: Message for when cooldown hasn't expired yet. Variables: {SECONDS}
# tooManyHomesMessage: Message for when user tries to set too many homes. Variables: {CURRENT}, {MAX}
# homeListMessage: Message for when home locations listed. Variables: {LIST}
# homeListOthersMessage: Message for when home locations for another player are listed. Variables: {PLAYER}, {LIST}
# econNotEnoughFunds: Message to use when a player does not have enough money for a command. Variables {AMOUNT}
# econDeductedForHome: Message to use when a player is charged for teleporting. Variables: {AMOUNT}
# econDeductForSet: Message to use when a player is charged for setting a home. Variables: {AMOUNT}
# deafult: Default settings for all users are stored here.
# warmup: Amount of time to wait before a /home command executes.
# cooldown: Amount of time to wait before /home can be used again.
# maxhomes: Maximum number of homes this group may have. Use -1 to signify no limit.
# disruptWarmup: Whether a players teleport will be cancelled if they are attacked. 0 for false, 1 for true
# setHomeCost: Amount to charge a player when setting their default home
#
# When editing this file for the first time, please duplicate the groups.default section
# for each of your defined Permissions groups.

YetiHome:
    enableHomeOnDeath: false
    permissiveGroupHandling: true
    enableEconomy: false
    loadChunks: false
    messages:
        tooManyParameters: 'Too many parameters.'
        defaultHomeSetMessage: 'You marked this area with your scent.'
        cannotDeleteDefaultHomeMessage: 'A yeti always needs a home.'
        homeSetMessage: 'Now the {HOME} smells like your land as well'
        homeDeletedMessage: 'The {HOME} no longer seems inviting.'
        noHomeMessage: 'Home {HOME} not set.'
        noDefaultHomeMessage: 'Home not set.'
        noPlayerMessage: 'Player {PLAYER} not found.'
        cooldownMessage: 'You may not teleport yet. Please wait another {SECONDS} seconds.'
        tooManyHomesMessage: 'Cannot set home location. You have already set {CURRENT} out of {MAX} homes.'
        econNotEnoughFunds: 'You did not have {AMOUNT} to do that.'
        econDeductedForHome: '{AMOUNT} was removed from your account for going home.'
        econDeductForSet: '{AMOUNT} was removed from your account for setting a home.'
        econNotEnoughFunds: 'You did not have {AMOUNT} to do that.'
    default:
        warmup: 0
        cooldown: 0
        maxhomes: 2
        disruptWarmup: true
        setHomeCost: 0
        setNamedHomeCost: 0
        homeCost: 0
        namedHomeCost: 0
        othersHomeCost: 0
    groups:
        default:
            warmup: 0
            cooldown: 0
            maxhomes: 2
            disruptWarmup: true
            setHomeCost: 0
            setNamedHomeCost: 0
            homeCost: 0
            namedHomeCost: 0